// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreFront.Models
{
    public partial class Address
    {
        public Address()
        {
            Orders = new HashSet<Orders>();
            UserDetails = new HashSet<UserDetails>();
        }

        public int AddressID { get; set; }
        public int? CountryID { get; set; }
        public int? StateID { get; set; }
        public int? Zip { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public int UserID { get; set; }
        public int? IsDeleted { get; set; }

        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<UserDetails> UserDetails { get; set; }
    }
}