// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreFront.Models
{
    public partial class Country
    {
        public Country()
        {
            Address = new HashSet<Address>();
            State = new HashSet<State>();
        }

        public int CountryID { get; set; }
        public string Country1 { get; set; }

        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<State> State { get; set; }
    }
}