// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreFront.Models
{
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public DateTime OrderDate { get; set; }
        public string ShipToName { get; set; }
        public int AddressID { get; set; }

        public virtual Address Address { get; set; }
        public virtual UserDetails User { get; set; }
    }
}