// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreFront.Models
{
    public partial class ProductStatus
    {
        public int ProductStatusID { get; set; }
        public string ProductStatus1 { get; set; }
    }
}