// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreFront.Models
{
    public partial class Products
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductDescription { get; set; }
        public short UnitsInStock { get; set; }
        public int CategoryID { get; set; }
        public string ProductImage { get; set; }
        public int? ProductStatusID { get; set; }

        public virtual Categories Category { get; set; }
    }
}