// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreFront.Models
{
    public partial class State
    {
        public State()
        {
            Address = new HashSet<Address>();
        }

        public int StateID { get; set; }
        public int CountryID { get; set; }
        public string State1 { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<Address> Address { get; set; }
    }
}