// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreFront.Models
{
    public partial class UserDetails
    {
        public UserDetails()
        {
            Orders = new HashSet<Orders>();
        }

        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? AddressID { get; set; }
        public string PhoneNumber { get; set; }
        public int? IsDeleted { get; set; }

        public virtual Address Address { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}